# Generated by Django 4.1.1 on 2023-05-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('twitter_url', models.URLField()),
                ('hometown', models.CharField(max_length=100)),
                ('disc_handle', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=200)),
            ],
        ),
    ]
