# Generated by Django 4.1.1 on 2023-05-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strangershq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='wallet_information',
        ),
    ]
