# Generated by Django 4.1.1 on 2023-05-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strangershq', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
