# Generated by Django 4.1.1 on 2023-05-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strangershq', '0004_rename_handle_user_twitter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='token_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='twitter_url',
            new_name='twitter_pfp_url',
        ),
    ]
