# Generated by Django 4.1.1 on 2023-05-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strangershq', '0005_rename_token_user_token_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='disc_handle',
            new_name='discord_handle',
        ),
    ]
