# Generated by Django 4.1.1 on 2023-05-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strangershq', '0006_rename_disc_handle_user_discord_handle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='wallet_information_testenv',
        ),
    ]
